# Generated by Django 4.2 on 2023-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basket_add_datetime_alter_basket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
